version: 2
jobs:
  build:
    docker:
      - image: docker:17-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t dsite-frontend .
      - run:
          name: Save Docker image
          command: docker save -o dsite-frontend.tar dsite-frontend
      - persist_to_workspace:
          root: .
          paths:
            - dsite-frontend.tar
  build-blackboxtest:
    docker:
      - image: docker:17-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t dsite-frontend-blackboxtest blackboxtest/
      - run:
          name: Save Docker image
          command: docker save -o dsite-frontend-blackboxtest.tar dsite-frontend-blackboxtest
      - persist_to_workspace:
          root: .
          paths:
            - dsite-frontend-blackboxtest.tar
  run-blackboxtest:
    docker:
      - image: docker:17-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker images
          command: |
            docker load -i /tmp/workspace/dsite-frontend.tar
            docker load -i /tmp/workspace/dsite-frontend-blackboxtest.tar
      - run:
          name: Start dsite-frontend
          command: |
            docker run -ditp 8080:8080 --name dsite-frontend dsite-frontend
            sleep 10 # let dsite-frontend start
      - run:
          name: Run tests
          command: docker run --network container:dsite-frontend dsite-frontend-blackboxtest
workflows:
  version: 2
  dsite-frontend:
    jobs:
      - build
      - build-blackboxtest
      - run-blackboxtest:
          requires:
            - build
            - build-blackboxtest
